apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicijnen-deployment
  labels:
    app: medicijnen
spec:
  replicas: 1 # aantal instanties van pod
  selector:
    matchLabels:
      app: medicijnen
    template:
      metadata:
        labels:
          app: medicijnen
        spec:
          containers:
            - name: medicijnen-container
              image: medicijnen
              # args [""]
              env: # wijzigen
                - name: SPRING_DATASOURCE_URL
                  value: "jdbc:postgresql://voorraad_db:5432/medicijnen"
                - name: SPRING_DATASOURCE_USERNAME
                  value: "admin"
                - name: SPRING_DATASOURCE_PASSWORD
                  value: "admin"
                - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
                  value: "kafka:9092"
                - name: SPRING_CLOUD_STREAM_BINDINGS_MEDICIJN_KRITISCHE_WAARDE_DESTINATION
                  value: "medicijn_kritische_waarde"
                - name: SPRING_CLOUD_STREAM_BINDINGS_PLAATS_BIJ_AFVAL_DESTINATION
                  value: "plaats_bij_afval"
                - name: SPRING_CLOUD_STREAM_BINDINGS_AFWIJKENDE_TEMPERATUUR_DESTINATION
                  value: "afwijkende_temperatuur"
                - name: SPRING_CLOUD_STREAM_BINDINGS_RESERVEER_BESTELLING_DESTINATION
                  value: "reserveer_bestelling"
                - name: SPRING_CLOUD_STREAM_BINDINGS_BEVESTIG_BESTELLING_DESTINATION
                  value: "bevestig_bestelling"
                - name: SPRING_CLOUD_STREAM_BINDINGS_GEEF_VRIJ_BESTELLING_DESTINATION
                  value: "geef_vrij_bestelling"
                - name: SPRING_CLOUD_STREAM_BINDINGS_RESERVEER_BESTELLING_RESPONSE_DESTINATION
                  value: "reserveer_bestelling_response"
                - name: SPRING_CLOUD_STREAM_BINDINGS_PLAATS_TERUG_DESTINATION
                  value: "plaats_terug"
                - name: EXTERNAL_API_KOELCEL_URI
                  value: "koelcelmonitor:8000"
          ports:
            - containerPort: 8080
              name: medicijnen

