apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper
spec:
  replicas: 1 # aantal instanties van pod
  selector:
    matchLabels:
      app: zookeeper
    template:
      metadata:
        labels:
          app: zookeeper
        spec:
          containers:
            - name: zookeeper-container
              image: confluentinc/cp-zookeeper
              env:
                - name: ZOOKEEPER_CLIENT_PORT
                  value: "2181"
          ports:
            - containerPort: 2181
              name: zookeeper

