apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-container
          image: brechtdbaer/gateway:latest
          imagePullPolicy: Always
          env:
            - name: MEDICIJNEN
              value: "medicijnen.default.svc.cluster.local:8080"
            - name: ORDER
              value: "order.default.svc.cluster.local:2222"
            - name: GEBRUIKERS
              value: "gebruikers.default.svc.cluster.local:3000"
            - name: KOELCELMONITOR
              value: "koelcelmonitor.default.svc.cluster.local:8000"
            - name: BESTELLINGEN
              value: "bestellingen.default.svc.cluster.local:8080"
            - name: TICKETDIENST
              value: "ticketdienst.default.svc.cluster.local:3000"
            - name: BOEKHOUDSDIENST
              value: "boekhoudsdienst.default.svc.cluster.local:3000"
            - name: VERZENDINGSDIENST
              value: "verzendingsdienst.default.svc.cluster.local:8080"
          ports: 
            - containerPort: 8089

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 8089
      targetPort: 8089
  externalIPs:
    - 10.2.0.179