apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-container
          image: gpveeckh/gateway:v1
          imagePullPolicy: Always
          env:
            - name: MEDICIJNEN
              value: "medicijnen.default.svc.cluster.local:8080"
            - name: BESTELLING
              value: "bestellingen.default.svc.cluster.local:8080"
            - name: ORDER
              value: "order.default.svc.cluster.local:2222"
            - name: koelcelmonitor
              value: "koelcelmonitor.default.svc.cluster.local:8000"
            - name: TICKETDIENST
              value: "ticketdienst.default.svc.cluster.local:3000"
            - name: BOEKHOUDSDIENST
              value: "boekhoudsdienst.default.svc.cluster.local:3000"
            ports: 
            - containerPort: 8089