apiVersion: apps/v1
kind: Deployment
metadata:
  name: gebruikers-db
  labels:
    app: gebruikers-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gebruikers-db
  template:
    metadata:
      labels:
        app: gebruikers-db
    spec:
      containers:
        - name: gebruikers-db
          image: 'mongo:4.4'
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "gebuikers"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "admin"
            - name: MONGO_INITDB_DATABASE
              value: "gebuikers"
          ports:
          - containerPort: 27017