apiVersion: apps/v1
kind: Deployment
metadata:
  name: gebruikers
  labels:
    app: gebruikers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gebruikers
  template:
    metadata:
      labels:
        app: gebruikers
    spec:
      containers:
        - name: gebruikers
          image: gpveeckh/gebruikers
          args: ["--db","mongodb://admin:admin@gebruikers-db-container:27017/gebruikers"]
          ports:
            - containerPort: 3000
