apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus
  labels:
    app: bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bus
  template:
    metadata:
      labels:
        app: bus
    spec:
      containers:
        - name: bus
          image: confluentinc/cp-kafka
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper.default.svc.cluster.local:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka.default.svc.cluster.local:9092" # checken
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          ports:
            - containerPort: 9092

---
            
apiVersion: v1
kind: Service
metadata:
  name: bus
spec:
  selector:
    app: bus
  ports:
    - port: 9092
      targetPort: 9092