apiVersion: apps/v1
kind: Deployment
metadata:
  name: koelcelmonitor
  labels:
    app: koelcelmonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koelcelmonitor
  template:
    metadata:
      labels:
        app: koelcelmonitor
    spec:
      containers:
        - name: koelcelmonitor
          image: gpveeckh/koelcelmonitor:v1
          args: ["--broker","bus.default.svc.cluster.local:9092"]
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: koelcelmonitor
spec:
  selector:
    app: koelcelmonitor
  ports:
    - port: 8000
      targetPort: 8000
  externalIPs:
    - 10.2.0.179