apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicijnen
  labels:
    app: medicijnen
spec:
  replicas: 
  selector:
    matchLabels:
      app: medicijnen
  template:
    metadata:
      labels:
        app: medicijnen
    spec:
      containers:
        - name: medicijnen-container
          image: gpveeckh/medicijnen:v3
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://medicijnen-db.default.svc.cluster.local:5432/medicijnen"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "bus.default.svc.cluster.local:9092"
            - name: EXTERNAL_API_KOELCEL_URI
              value: "koelcelmonitor.default.svc.cluster.local:8000"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: medicijnen
spec:
  selector:
    app: medicijnen
  ports:
    - port: 8081
      targetPort: 8080
  externalIPs:
    - 10.2.0.179