apiVersion: apps/v1
kind: Deployment
metadata:
  name: verzendingsdienst
  labels:
    app: verzendingsdienst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verzendingsdienst    
  template:
    metadata:
      labels:
        app: verzendingsdienst
    spec:
      containers: 
        - name: verzendingsdienst
          image: pkukoba/verzendingsdienst:latest
          env: 
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "bus.default.svc.cluster.local:9092"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://pakketten.default.svc.cluster.local:3306/pakketten"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
          ports:
           - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: verzendingsdienst
spec:
  selector:
    app: verzendingsdienst
  ports:
    - port: 8082
      targetPort: 8080
  externalIPs:
    - 10.2.0.179
