version: "3"
services:
  voorraad_db:
    image: postgres:13.1
    container_name: voorraad_db
    # https://hub.docker.com/_/postgres
    restart: always
    environment:
      - POSTGRES_DB=medicijnen
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      # noodzakelijk voor protocol, die geeft aan waar zijn broker zich bevindt
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - 9092:9092
  