apiVersion: apps/v1
kind: Deployment
metadata:
  name: gebruikers-deployment
  labels:
    app: gebruikers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gebruikers
    template:
      metadata:
        labels:
          app: gebruikers
        spec:
          containers:
            - name: gebruikers-container
              image: confluentinc/cp-zookeeper
              args: ["--db","mongodb://admin:admin@gebruikers_db:27017/gebruikers"]
          ports:
            - containerPort: 3000
              name: gebruikers

