apiVersion: apps/v1
kind: Deployment
metadata:
  name: koelcelmonitor-deployment
  labels:
    app: koelcelmonitor
spec:
  replicas: 1
  matchLabels:
    app: koelcelmonitor
    template:
      metadata:
        labels:
          app: koelcelmonitor
      spec:
        containers:
          - name: koelcelmonitor
            image: koelcelmonitor
            args: ["--broker","kafka:9092"]
            ports:
              - containerPort: 8000
