apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-container
          image: pacalleb/order:latest
          args: ["--spring.datasource.url=jdbc:mysql://magazijn-db.default.svc.cluster.local:3306/Order"]
          imagePullPolicy: Always
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "bus.default.svc.cluster.local:9092"
            - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
              value: "admin"
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://admin:admin@orderdb.default.svc.cluster.local/orders?authSource=admin"  
          ports: 
            - containerPort: 2222

---

apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
    - port: 2222
      targetPort: 2222
  externalIPs:
    - 10.2.0.179