apiVersion: apps/v1
kind: Deployment
metadata:
  name: magazijn-db
  labels:
    app: magazijn-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magazijn-db
  template:
    metadata:
      labels:
        app: magazijn-db
    spec:
      containers:
        - name: magazijn-db
          image: 'mysql:5.7'
          args: ["--default-authentication-plugin=mysql_native_password"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DATABASE
              value: "Order"
          ports:
          - containerPort: 3306
            targetPort: 3306

---

apiVersion: v1
kind: Service 
metadata:
  name: magazijn-db
spec: 
  selector:
    app: magazijn-db
  ports:
    - port: 3306
      targetPort: 3306
